# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# SKU: 3272018

target 'Parti' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Parti
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  # Pods for authentication
  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  
  # Pods for music
  pod 'Alamofire', '~> 4.7'
  
  # Pods for UI
  pod 'MaterialComponents'

  # Pods for Crashlytics
  pod 'Fabric', '~> 1.7.6'
  pod 'Crashlytics'

  target 'PartiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
