# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Parti' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Parti
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  # Pods for authentication
  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

  target 'PartiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
